<a href="https://colab.research.google.com/github/soiejung/PythonStudy/blob/main/Numpy_Pandas_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1-1. 다음은 행별로 학생의 모의고사 점수를 담고 있는 행렬입니다. 이 점수들에 가중치를 두어 다음 연산하여 모의고사의 점수를 예측하려 합니다. 다음 모의고사는 1, 3회차와 유사한 난이도를 보일 것으로 예상되므로  1회차에 40%, 2회차에 20%, 3회차에 40%의 가중치를 두어 계산한다면, 각 학생의 4회차 모의고사 점수는 몇점이 될지 예측해보세요.


    # 한행은 한학생의 과거 모의고사 점수
    [80,90,70],
    [81,93,72],
    [71,73,62],
    [61,70,72]


In [ ]:
#넘파이
import numpy as np

x = np.array([
    [80,90,70],
    [81,93,72],
    [71,73,62],
    [61,70,72]
])

In [ ]:
np.average(x, weights=[0.4, 0.2, 0.4], axis=1)

array([78. , 79.8, 67.8, 67.2])

In [ ]:
w = np.array([0.4, 0.2, 0.4])
x @ w # 벡터의 내적을 위한 넘파이 연산부호

array([78. , 79.8, 67.8, 67.2])

벡터의 내적 :
$(a_1, a_2)\cdot(b_1, b_2) = a_1 b_1 + a_2 b_2$

a.dot(b)

In [ ]:
yhat = x.dot(w)

In [ ]:
yhat = yhat.reshape(-1, 1)

1-2. 다음은 실제 학생들의 4회차 모의고사 시험점수입니다. 각 학생의 시험점수는 위에서 예측한 점수와 얼마나 차이가 나는지 계산해보세요.

    y = np.array([
        # 실제 시험에서의 점수
        [77],
        [80],
        [71],
        [65]
    ])


In [ ]:
y = np.array([
    # 실제 시험에서의 점수
    [77],
    [80],
    [71],
    [65]
]) # 4회차 모의고사의 점수

In [ ]:
z = y - yhat

1-3. 실제 점수 y와 예측점수 사이의 분산을 구해보세요.

In [ ]:
sum((y - yhat)**2) / len(z)

array([4.03])

In [ ]:
np.var(y-yhat)

4.027500000000008

1-4. 실제 점수 y와 예측점수 사이의 표준편차를 구해보세요.

In [ ]:
(sum((y - yhat)**2) / len(z)) ** 0.5

array([2.00748599])

In [ ]:
np.std(y-yhat)

2.0068632240389497

1-5. 위의 배열 x의 마지막 열에 4회차 모의고사 점수를 연결해보세요.

In [ ]:
y = np.array([
    # 실제 시험에서의 점수
    [77],
    [80],
    [71],
    [65]
]) # 4회차 모의고사의 점수

In [ ]:
x = np.concatenate([x, y], axis=1)

1-6. 각 학생들의 1,3회차 모의고사 결과들만을 출력해보세요.

In [ ]:
x

array([[80, 90, 70, 77],
       [81, 93, 72, 80],
       [71, 73, 62, 71],
       [61, 70, 72, 65]])

In [ ]:
  x[:, [0, 2]]

array([[80, 70],
       [81, 72],
       [71, 62],
       [61, 72]])

In [ ]:
x

array([[80, 90, 70, 77],
       [81, 93, 72, 80],
       [71, 73, 62, 71],
       [61, 70, 72, 65]])

In [ ]:
x[:, [True, False, True, False]]

array([[80, 70],
       [81, 72],
       [71, 62],
       [61, 72]])

In [ ]:
x[:, ::2]

array([[80, 70],
       [81, 72],
       [71, 62],
       [61, 72]])

2. 전처리 맛보기

- 다음의 arr을 오름차순으로 정렬해보세요.

In [ ]:
#nan inf
arr = np.array([np.inf , np.nan, 4,5,7,8.1])

In [ ]:
np.array(sorted(arr)) # np.inf, np.nan을 파이썬의 기본 정렬 함수로는 정렬 불가

array([inf, nan, 4. , 5. , 7. , 8.1])

In [ ]:
np.sort(arr)

array([4. , 5. , 7. , 8.1, inf, nan])

In [ ]:
arr.dtype

dtype('float64')


- 다음의 arr을 내림차순으로 정렬해보세요.

In [ ]:
-np.sort(-arr)

array([inf, 8.1, 7. , 5. , 4. , nan])

- 아래 함수들은 전처리 과정에서 nan, infinite 값을 구분하기 위해 사용하는 함수들입니다. 해당 함수들을 사용하여 arr에 있는 무한대와 nan 값들을 0으로 대체해보세요.

```
np.isinf()
np.isnan()
np.isfinite()
```

- 무한대값 찾기

In [ ]:
arr = np.array([np.inf, np.nan, 4. , 5. , 7. , 8.1])

In [ ]:
np.isinf(arr)

array([ True, False, False, False, False, False])

In [ ]:
arr[np.isinf(arr)] = 0

In [ ]:
arr

array([0. , nan, 4. , 5. , 7. , 8.1])

- nan 값 찾기

In [ ]:
np.isnan(arr)

array([False,  True, False, False, False, False])

- 셀수 있는 정상 수치만 찾아보세요.

In [ ]:
np.isfinite(arr) # np.inf, np.nan 을 모두 False 로 반환하는

array([False, False,  True,  True,  True,  True])

- 위에서 찾은 셀수 있는 정상 수치가 아닌 값들을 0으로 변경해보세요.

In [ ]:
arr[np.isfinite(arr) == False] = 0

In [ ]:
arr[~np.isfinite(arr)] # ~ : 인덱싱할 때 not 을 의미

array([], dtype=float64)

In [ ]:
arr

array([0. , 0. , 4. , 5. , 7. , 8.1])

3. Pandas 복습

# 실습

In [ ]:
# dataframe name : countries
data = {'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']}

In [ ]:
import numpy as np
import pandas as pd

countries = pd.DataFrame(data)
countries

country  population    area    capital
0         Belgium        11.3   30510   Brussels
1          France        64.3  671308      Paris
2         Germany        81.3  357050     Berlin
3     Netherlands        16.9   41526  Amsterdam
4  United Kingdom        64.9  244820     London

In [ ]:
countries.head()

country  population    area    capital
0         Belgium        11.3   30510   Brussels
1          France        64.3  671308      Paris
2         Germany        81.3  357050     Berlin
3     Netherlands        16.9   41526  Amsterdam
4  United Kingdom        64.9  244820     London

In [ ]:
countries.tail()

country  population    area    capital
0         Belgium        11.3   30510   Brussels
1          France        64.3  671308      Paris
2         Germany        81.3  357050     Berlin
3     Netherlands        16.9   41526  Amsterdam
4  United Kingdom        64.9  244820     London

In [ ]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     5 non-null      object 
 1   population  5 non-null      float64
 2   area        5 non-null      int64  
 3   capital     5 non-null      object 
dtypes: float64(1), int64(1), object(2)
memory usage: 288.0+ bytes


In [ ]:
countries.describe(include='all')

country  population           area   capital
count         5    5.000000       5.000000         5
unique        5         NaN            NaN         5
top     Belgium         NaN            NaN  Brussels
freq          1         NaN            NaN         1
mean        NaN   47.740000  269042.800000       NaN
std         NaN   31.519645  264012.827994       NaN
min         NaN   11.300000   30510.000000       NaN
25%         NaN   16.900000   41526.000000       NaN
50%         NaN   64.300000  244820.000000       NaN
75%         NaN   64.900000  357050.000000       NaN
max         NaN   81.300000  671308.000000       NaN

In [ ]:
countries.describe().T

count       mean            std      min      25%       50%  \
population    5.0      47.74      31.519645     11.3     16.9      64.3   
area          5.0  269042.80  264012.827994  30510.0  41526.0  244820.0   

                 75%       max  
population      64.9      81.3  
area        357050.0  671308.0

실습1 : 인구밀도를 의미하는 `density` 칼럼을 추가하세요. (주의: 현재 'population' 칼럼은 100만 단위로 표기되어 있습니다)

In [ ]:
countries

country  population    area    capital  density
0         Belgium        11.3   30510   Brussels    370.0
1          France        64.3  671308      Paris    100.0
2         Germany        81.3  357050     Berlin    230.0
3     Netherlands        16.9   41526  Amsterdam    410.0
4  United Kingdom        64.9  244820     London    270.0

In [ ]:
#칼럼 추가 / 변경 해보기
# 파생변수 : 사물이 어떤 근원으로부터 갈려 나와 생김.
# density라는 새로운 차원을 만들어냈음 - 기존의 데이터들을 참고해서 새로운 데이터를 만들어냄
countries['density'] = round((countries.population * 1000000)/ countries.area).astype(int)
countries

country  population    area    capital  density
0         Belgium        11.3   30510   Brussels      370
1          France        64.3  671308      Paris       96
2         Germany        81.3  357050     Berlin      228
3     Netherlands        16.9   41526  Amsterdam      407
4  United Kingdom        64.9  244820     London      265

실습2 : 인구밀도가 300을 초과하는 국가(country)의 수도(capital)과 인구(population)을 선택해주세요.

</div>

In [ ]:
countries.density > 300

0     True
1    False
2    False
3     True
4    False
Name: density, dtype: bool

In [ ]:
# 불린인덱싱 필요
countries.loc[countries.density > 300, ['capital', 'density']]

capital  density
0   Brussels      370
3  Amsterdam      407

실습3 : 'density_ratio' 칼럼을 추가해주세요. (density_ratio = 인구밀도/평균 인구밀도)

In [ ]:
countries.density.mean()

273.2

In [ ]:
countries['density_ratio'] = countries.density / countries.density.mean()

In [ ]:
countries

country  population    area    capital  density  density_ratio
0         Belgium        11.3   30510   Brussels      370       1.354319
1          France        64.3  671308      Paris       96       0.351391
2         Germany        81.3  357050     Berlin      228       0.834553
3     Netherlands        16.9   41526  Amsterdam      407       1.489751
4  United Kingdom        64.9  244820     London      265       0.969985

실습4 : 영국(United Kingdom)의 수도(capital)를 'Cambridge'로 변경해주세요.

In [ ]:
# 열 -> 행
countries.capital[4] = 'Cambridge'

'London'

In [ ]:
countries.capital.replace(['London'], ['Cambridge'], inplace=True)

In [ ]:
countries

country  population    area    capital  density  density_ratio
0         Belgium        11.3   30510   Brussels      370       1.354319
1          France        64.3  671308      Paris       96       0.351391
2         Germany        81.3  357050     Berlin      228       0.834553
3     Netherlands        16.9   41526  Amsterdam      407       1.489751
4  United Kingdom        64.9  244820  Cambridge      265       0.969985

실습 5: 수도가 7글자 이상인 국가들을 표시해주세요. (힌트: string의 len( )를 사용하세요.)

In [ ]:
type(countries.capital[0])

str

In [ ]:
'사과나무'.find('무')

3

In [ ]:
str.find('사과나무', '무')

3

In [ ]:
countries.capital

0     Brussels
1        Paris
2       Berlin
3    Amsterdam
4    Cambridge
Name: capital, dtype: object

In [ ]:
len('Brussels')

8

In [ ]:
# 불린 인덱싱으로 값을 찾는다
countries.capital.str.len() >= 7
countries[countries.capital.str.len() >= 7]

country  population    area    capital  density  density_ratio
0         Belgium        11.3   30510   Brussels      370       1.354319
3     Netherlands        16.9   41526  Amsterdam      407       1.489751
4  United Kingdom        64.9  244820  Cambridge      265       0.969985

실습6: 수도에 'am' 이 포함되는 국가들을 표시해주세요. (힌트: string의 contains( )를 사용하세요.)

In [ ]:
countries.capital.str.contains('am')

0    False
1    False
2    False
3     True
4     True
Name: capital, dtype: bool

In [ ]:
countries[countries.capital.str.contains('am')]

country  population    area    capital  density  density_ratio
3     Netherlands        16.9   41526  Amsterdam      407       1.489751
4  United Kingdom        64.9  244820  Cambridge      265       0.969985

In [ ]:
countries.loc[countries.capital.str.contains('am'), ['country']]
# 열, 행 순으로 값을 받고 싶기 때문에

country
3     Netherlands
4  United Kingdom