<a href="https://colab.research.google.com/github/soiejung/PythonStudy/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9DI_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://lh3.googleusercontent.com/jS2nj0Ju7rvJJangnpFrnveoLlMAVc-Ee-k38WW3bRT1rpOooDKa8c3Uh2hZs5j6-XNc1ZFry07GtQTX8sYRpyZGgz8TZuBpGw75pAZqSKQRSfKA0Isy3I-222AHDlZa1WNAvFGmQLfeR4S96qK3agRN-br82Od1243W4uVZbFmbkZPykYy4_qDeE2UrbT1nVr8QZccLXjjtjiJRM8WQ_8eZFSRUBP1BMQg5AG6l7tdGXuWlQDmqFOFcDcEQE5ZX30N7TIcDSOiMWjp0gGZgtMfaR983h4NP8dUp-ej-Vo1D4FSpa_zTpjvKRrpbfnVir1LpIw0yC9OjD7aCMtLcul9Npe-voMkiJgz5XNvFatCgq5WmfcoaDDvkkEQZgp7LQoOqqprzvdItdiyWagMtCVQONtypoZhc2kQQkfav2M0sC9kG4AXDJ6nOlpi8iSbJSVVPKHN9wzGzN1gxo2dDtaua9VfHd5MTOWiRV6ArL6pzwzSzAPSAgUFZZhc4RHGzk5ChHsJBaO3gzvn8GF4Cr7P7GahgXEhw98u1Z0VlNqDmp37B4cUHm5dujBm7jQXGTvPqM5zuDHwiviFId6OMjcjW6xZNckM9_KM8opmUYN_RKP-YPs51qrz9NVksS73JOhHpBHtVQMDCFycT6ZSKv-zdwZN7_FW7=w2160-h856-no)

## Numpy: Numeric + Python의 약자, 수학 및 과학 연산 라이브러리
- 배열이나 행렬 계산에 필요한 함수 제공
- 수열 데이터를 다룰 때 용이, 이후에 Pandas에서 DataFrame 형태로 사용함
- 다차원 배열(Array)을 다룰 때 주로 사용함 (인공 신경망, 비정형 데이터 처리, 자연어 처리 등)
- 코어 부분이 C로 구현되어 동일한 연산을 하더라도 Python에 비해 속도가 빠름
- 라이브러리에 구현되어있는 함수들을 활용해 짧고 간결한 코드 작성 가능

## 리스트 자료형과의 차이

In [ ]:
test = [15, 20, 25] # 오늘 입학시험을 본 3명의 점수

In [ ]:
test

[15, 20, 25]

In [ ]:
type(test)

list

In [ ]:
!pip install numpy # 넘파이 설치 - 코랩은 데이터분석 관련 패키지들을 미리 깔아서 우리에게 제공해줌

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

실습1 : test변수에 들어있는 점수들의 합(testTotal)과, 평균(testAvg)을 구하여 출력하세요.

In [ ]:
testTotal = 0

for tes in test:
    testTotal += tes

testTotal

60

In [ ]:
sum(test)

60

In [ ]:
len(test)

3

In [ ]:
testAvg = testTotal / len(test)

In [ ]:
testAvg

20.0

빼먹은 30점짜리 시험지를 발견했다!! 이 학생의 성적을 추가한 점수들의 합과 평균을 구하려면 어떻게 해야 할까요?

새로운 변수를 추가해야 합니다.

실습2. 변수 test에 30을 추가해주세요.

In [ ]:
test.append(30)

실습3. 새로운 학생이 본 시험점수를 더해 총합과 평균을 구해주세요.

In [ ]:
testTotal = sum(test)

In [ ]:
testAvg = sum(test) / len(test)

실습4. 그렇다면 시험문제의 오류가 발견되어 모두 정답처리를 해 모든 학생의 점수를 5점씩 올려줘야 하는 상황에서는 어떻게 해야할까요?

In [ ]:
test + 5

TypeError: ignored

**반복문**

In [ ]:
test2 = []

for tes in test:
    print(tes)
    test2.append(tes+5)

test = test2

15
20
25
30


실습(복습) 5. 위의 반복문을 List Comprehension으로 만들어보세요.

In [ ]:
test = [15, 20, 25]

In [ ]:
test = [x+5 for x in test]

In [ ]:
test

[20, 25, 30]

In [ ]:
test = list(map(lambda x : x+5, test))

In [ ]:
test

[20, 25, 30]

## ndarray의 특징
- Numpy의 데이터 타입 중 하나로, 리스트와 비슷한 형식의 구조적인 데이터
- 이중 구조의 배열이나 행렬(Matrix)처럼 사용이 가능하며, 수학/과학 연산을 모두 지원한다.

**NumPy** 모듈을 사용하면 다차원배열을 효율적으로 다룰 수 있습니다.

`import numpy as np` 형태로 import합니다.

- test = [15, 20, 25, 30]

In [ ]:
import numpy as np # np는 numpy를 의미하는 게 약속처럼 되어있습니다.
# from numpy import * -> 이 경우 파이썬의 기본 내장함수와 겹치는 이름들을 numpy가 덮어쓰기 때문에 권장하지는 않습니다

In [ ]:
# ndarray - numpy가 제공하는 특수 자료타입
test = np.array([15, 20, 25, 30])

In [ ]:
test = [15, 20, 25, 30]

In [ ]:
test2 = np.array(test)

In [ ]:
test2

array([15, 20, 25, 30])

In [ ]:
type(test2)

numpy.ndarray

In [ ]:
test

array([15, 20, 25, 30])

In [ ]:
range(5,31,5)

range(5, 31, 5)

In [ ]:
test2 = np.array(range(15,31,5))

In [ ]:
test2

array([15, 20, 25, 30])

In [ ]:
# np.arange - ndarray 수열을 만들어주는 메소드
test1 = np.arange(15, 31, 5) # 시작점, 끝+1, 스텝, r이 1개!!
test1

array([15, 20, 25, 30])

In [ ]:
range(15, 31, 0.1)

TypeError: ignored

In [ ]:
np.arange(15, 31, 0.1) # 플레인 파이썬의 range 와는 다르게 float 으로도 수열을 구현할 수 있습니다

array([15. , 15.1, 15.2, 15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16. ,
       16.1, 16.2, 16.3, 16.4, 16.5, 16.6, 16.7, 16.8, 16.9, 17. , 17.1,
       17.2, 17.3, 17.4, 17.5, 17.6, 17.7, 17.8, 17.9, 18. , 18.1, 18.2,
       18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. , 19.1, 19.2, 19.3,
       19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1, 20.2, 20.3, 20.4,
       20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1, 21.2, 21.3, 21.4, 21.5,
       21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3, 22.4, 22.5, 22.6,
       22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4, 23.5, 23.6, 23.7,
       23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4, 24.5, 24.6, 24.7, 24.8,
       24.9, 25. , 25.1, 25.2, 25.3, 25.4, 25.5, 25.6, 25.7, 25.8, 25.9,
       26. , 26.1, 26.2, 26.3, 26.4, 26.5, 26.6, 26.7, 26.8, 26.9, 27. ,
       27.1, 27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8, 27.9, 28. , 28.1,
       28.2, 28.3, 28.4, 28.5, 28.6, 28.7, 28.8, 28.9, 29. , 29.1, 29.2,
       29.3, 29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30

In [ ]:
test = np.arange(15, 31, 5)

In [ ]:
test

array([15, 20, 25, 30])

In [ ]:
test1

array([15, 20, 25, 30])

In [ ]:
test2 = np.array([test, test1])

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

numpy 사이즈에 관한 변수들 살펴보기

In [ ]:
dir(test2)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

In [ ]:
test2.shape # (2, 4)  2 행 4 열  - 2차원

(2, 4)

In [ ]:
test

array([15, 20, 25, 30])

In [ ]:
test.shape # (4,)   - 1

(4,)

In [ ]:
test2.ndim # n-dimension  차원을 알려주는 속성

2

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

In [ ]:
test2.dtype # dtype('int64') - 데이터타입

dtype('int64')

In [ ]:
test2.itemsize # 8byte  (64bit) - 방 하나에 몇바이트 용량인지

8

In [ ]:
test.itemsize

8

In [ ]:
test2.size # 8 몇개의 원소를 가지고 있는지(방이 몇개)

8

In [ ]:
test.size # 4

4

각 원소에 5를 더하려면

In [ ]:
test2 + 5 # broadcasting

array([[20, 25, 30, 35],
       [20, 25, 30, 35]])

In [ ]:
test2 - 5

array([[10, 15, 20, 25],
       [10, 15, 20, 25]])

In [ ]:
test2 ** 5

array([[  759375,  3200000,  9765625, 24300000],
       [  759375,  3200000,  9765625, 24300000]])

In [ ]:
test2 / 5

array([[3., 4., 5., 6.],
       [3., 4., 5., 6.]])

In [ ]:
test2.append(35)

AttributeError: ignored

In [ ]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [ ]:
test3 = np.append(test2, 35)

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

In [ ]:
np.append(test2, [[35], [40]], 1)

array([[15, 20, 25, 30, 35],
       [15, 20, 25, 30, 40]])

In [ ]:
np.append(test2, [[35], [40]], axis=1)

array([[15, 20, 25, 30, 35],
       [15, 20, 25, 30, 40]])

In [ ]:
np.append(test2, [[35,40, 45, 50]], axis=0)

array([[15, 20, 25, 30],
       [15, 20, 25, 30],
       [35, 40, 45, 50]])

In [ ]:
[1,2,3].append(4)

In [ ]:
# 파이썬의 내장함수 append는 리스트를 파괴하고 요청한 원소를 추가하는 파괴적 함수
# 91년에 만들어진 언어라서 속도 때문에 원본을 2개 복사할 수 없으니까
# append 를 했을 때 원본을 변경하는 방식으로 구현이 되어있었습니다

# 데이터 관련 패키지들은 내장 append만큼 메모리를 아낄 필요가 없기 때문에
# 원본은 그대로 두고, 비파괴적으로 구현이 된다

AttributeError: ignored

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

In [ ]:
np.delete(test2, 0)

array([20, 25, 30, 15, 20, 25, 30])

In [ ]:
np.delete(test2, 0, axis=0) # axis=0 : 행

array([[15, 20, 25, 30]])

In [ ]:
np.delete(test2, 0, axis=1) # axis=1 : 열

array([[20, 25, 30],
       [20, 25, 30]])

In [ ]:
np.delete(test2, 1)

array([15, 25, 30, 15, 20, 25, 30])

In [ ]:
np.delete(test2, -1)

array([15, 20, 25, 30, 15, 20, 25])

자료의 차원을 확인하는 것은 매주 중요합니다.
- 자료의 차원이 다르면, 알고리즘이 동작하지 않게 됩니다.
  - 알고리즘을 직접 작성하지는 않고, 잘 만들어진 라이브러리를 이용하게 됩니다.
  - 자료의 차원을 고려해서 사용을 해야 합니다.


### 2차원 배열
- 우리가 주로 다루게 되는 배열은 2차원입니다.
  - 자료가 대부분 2차원입니다.
  - 수업시간에도 2차원 배열까지만 확인을 합니다.
- 리스트와 동일하게, 배열의 원소로 배열을 갖는 배열 정도로 이해

NumPy에 구현된 메서드를 활용해 합이나 평균도 쉽게 구할 수 있습니다.

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

In [ ]:
test2.T

array([[15, 15],
       [20, 20],
       [25, 25],
       [30, 30]])

In [ ]:
test2.transpose()

array([[15, 15],
       [20, 20],
       [25, 25],
       [30, 30]])

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

In [ ]:
np.sum(test2, 0)

array([30, 40, 50, 60])

In [ ]:
np.sum(test2, 1)

array([90, 90])

In [ ]:
test2.sum()

180

In [ ]:
test2.sum(1)

array([90, 90])

In [ ]:
test2.mean()

22.5

In [ ]:
test2.mean(0)

array([15., 20., 25., 30.])

In [ ]:
test2.mean(1)

array([22.5, 22.5])

In [ ]:
test2.var() # 분산

31.25

In [ ]:
test2.std() # 표준편차

5.5901699437494745

In [ ]:
test2.max()

30

In [ ]:
test2.min()

15

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

In [ ]:
test2.argmax(1) # 가장 큰 값이 있는 인덱스번호를 출력

array([3, 3])

In [ ]:
test2.argmin(0)

array([0, 0, 0, 0])

![alt text](https://lh3.googleusercontent.com/zXC7mbgObMUkQoUnkfMvog5wU8Qh2bvLEwINZo7eilDpq_aun8c3D_qCvaCZhQQLnC-iz7XxFP3iWylf3RZWNsKUaw2MFU0c4Oiu3cbZIPM4AsgSSUVYlDzZKVgG-ldbaEt2vty-cqaHNqrIYNPjsN6n8gT5XbJPqEk5GJjjTfL61t5ugfaDtHjbskwoZm45x8xbWJgkilc8fZ70hWGr8tpskk_5P4G3dI9zy0-ZNTDF9R2nGknAjcmCT3cP5nKhL0YM8mhhbWxS7jTotR1A-hKBPRXbu-5tFa1W54F8k4Do17Wvhz_JNaj0EX-5z0BT8ryE6XPvsJd4vlQAAzwYKdy9oIL7KYzTiIy3vi7MicCg7opIc87ueczPBpZUv2vczrUzzOT-6Yczc9Ay2UPvzyS6SmB2QJI2gGXXvdRFZAElecn83X98psuIHAGx7xii7OplLOQLNaDN3o0tCt4v0e2mgnP8zU87MfUGMCgs-zJwCZYeJz-2rt1EHGGk0IuiiDJQ-R_X91KUE1Z76VOHOjBt_saj-UJ40dTB2w_ITArQa1dH2GhPZCz7wC4_UmwYlr1BHUiohA1ByDBHRB2cA8sBF5MU3s7F1KKWPQUcBQqf2NhQgUJTYWnvWUrgqdmvEKRVRiXwqlJiwGVc1_nCFUAOtzXqLtJAvT0mlKso-GUEPy6NPFjR-Yvv4ci_QFfhtUh87MyVYTEphY7xcNwTaswPqw=w652-h341-no)

### 실습. numpy의 ndarray를 활용하여 위의 실습을 다시 해 볼게요!

실습0 : [15, 20, 25]이 들어있는 ndarray를 만들어주세요.

In [ ]:
a = [15, 20, 25]

In [ ]:
test = np.array(a)

In [ ]:
test

array([15, 20, 25])

In [ ]:
type(test)

numpy.ndarray

실습1 : test변수에 들어있는 점수들의 합(testTotal)과, 평균(testAvg)을 구하여 출력하세요.

In [ ]:
testTotal = np.sum(test)

In [ ]:
testTotal = test.sum()

In [ ]:
testTotal

60

In [ ]:
testAvg = test.mean()

In [ ]:
testAvg

20.0

In [ ]:
'사과나무'.find('무')

3

In [ ]:
str.find('사과나무', '무')

3

빼먹은 30점짜리 시험지를 발견했다!! 이 학생의 성적을 추가한 점수들의 합과 평균을 구하려면 어떻게 해야 할까요?

새로운 변수를 추가해야 합니다.

실습2. 변수 test에 30을 추가해주세요.

In [ ]:
test = np.append(test, 30) # 결과를 리턴해준다는 건 -> 원본이 바뀌지 않았다는 의미

실습3. 새로운 학생이 본 시험점수를 더해 총합과 평균을 구해주세요.

In [ ]:
test.sum()

90

In [ ]:
test.mean() # ndarray라는 넘파이의 자료형이 가지고 있는 인스턴스메소드들로 웬만한 연산 가능

22.5

실습4. 그렇다면 시험문제의 오류가 발견되어 모두 정답처리를 해 모든 학생의 점수를 5점씩 올려줘야 하는 상황에서는 어떻게 해야할까요?

In [ ]:
test + 5 # 브로드캐스팅

array([20, 25, 30, 35])

완벼크.

### (참고) ndarray가 list보다 빠른 이유

![alt text](https://lh3.googleusercontent.com/JD1ljKEm4S_4hvIu8XqTLUw75AjB6K-ElhXY6oMqBiPVEPIkNpHjlMLKsTbpWMIXOZ1X3Ompb-v3lI5FHqlyWWOFR0Pg3vLsio9_8OSgFoAywjGAC6oY85kCahlx-rJtSqW9M3szyXBVjrnlUYIo3opwX7ch7BYaV6sLReXAOwcJThS4f-E-PQWOzwSsCerL_-QEi_wcEV_4Aef_q0u9lrcjvZX-OwW-AcSILKPIB3yoZar4zTTOPHz-miQ4yq2gOktHY1wR4izuJ5SmIT2feKEdP6sD5So8I24vdt1mKKjro3fQenb9ExtH-zAxlJQarxaDnklts7801rG56sa6sE69ZJBp3ZzJ8qr59SM1xf2t9dU1WHcIvMWM5g39B85aIYHRCFmqfwaAx6Gl8x7To_33nyLpc8hA6gIbPQ46O6N_I3-s2G_t5E1dt9mEr0v9fgnco5ib53RP7myVnH6prsSOP4n0hzSvf_gBvKsYIJ2TJA-631XcIR5K7VgE6kycjbVGtTlfDn5fTbVbjgJyIR2xhjPFQ85rxpLnPD0NLE8LzGzjA7bo3CJiBjd0CUHbjbUbUINtLHm8H8lT9U7vZIEzLSIA4dvO3SujTC8R8F7dPBO5Bc91VTWF1mqUftGeWmIdJ61E-KlKb6lRYnRdNq55scpLa3sX2Y2v3tCFq4uHvUM2VO4gkyi_9WNZciyoq1gQD8e9_Ig3aUsWdU87JJMQNw=w638-h479-no)

> (source: https://image.slidesharecdn.com/numpy20160519-160516164831/95/numpy-8-638.jpg)

**파이썬 list가 느린 이유**

- 파이썬 리스트는 결국 포인터의 배열
- 경우에 따라서 각각 객체가 메모리 여기저기 흩어져 있음
- 그러므로 캐시 활용이 어려움

**NumPy ndarray가 빠른 이유**

- ndarray는 타입을 명시하여 원소의 배열로 데이터를 유지
- 다차원 데이터도 연속된 메모리 공간이 할당됨
- 많은 연산이 dimensions과 strides를 잘 활용하면 효율적으로 가능
- ndarray 구현 방식을 떠올리면 어떻게 성능을 낼 수 있는지 상상 가능



(참고2) strides
- '걸음걸이, 보폭'이라는 뜻을 가지고 있는 단어
- numpy에서는, 각 dimensions를 건너가는데 몇 bytes나 뛰어넘어야 하는지에 대한 정보

    예를들어 [[1,2,3],[4,5,6]] 이라는 2차원의 array가 있다면 strides를 사용하면 (dimensions 간의 간격, 앨리먼트간의 간격) 으로 결과가 출력된다. 각 dimensions 간의 간격은 [1,2,3] 의 용량과 같으므로 4바이트인 int32형 3개 = 12 bytes인 것.

In [ ]:
test

array([15, 20, 25, 30])

In [ ]:
test.strides # (8,)

(8,)

In [ ]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8]])

In [ ]:
a.ndim # 2차원 데이터

2

In [ ]:
a.shape # (2행, 4열로 이루어진

(2, 4)

In [ ]:
a.itemsize # 원소 하나당 8byte를 할당합니다

8

In [ ]:
a.size # 총 8개가 들어있습니다

8

In [ ]:
a.strides # (32, 8) (dimension 간의 간격, 엘리먼트 간의 간격) #  [1, 2, 3, 4]

(32, 8)

In [ ]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
a.dtype   # dtype('int64')

dtype('int64')

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8]], dtype='int8')

In [ ]:
a.dtype

dtype('int8')

In [ ]:
a.ndim # 2차원 데이터

2

In [ ]:
a.shape # (2행, 4열로 이루어진

(2, 4)

In [ ]:
a.itemsize # 원소 하나당 1byte를 할당합니다

1

In [ ]:
a.size # 총 8개가 들어있습니다

8

In [ ]:
a.strides # (4, 1) (dimension 간의 간격, 엘리먼트 간의 간격) #  [1, 2, 3, 4]

(4, 1)

In [ ]:
b = np.array([1, 2, 3., 4])

In [ ]:
b.dtype # dtype('float64')

dtype('float64')

In [ ]:
b = np.array([1, '2', 3, 4])

In [ ]:
b.dtype # dtype('<U21') - Unicode 문자열임

dtype('<U21')

In [ ]:
b

array(['1', '2', '3', '4'], dtype='<U21')

In [ ]:
b = np.array([True, 2, 3, 4])

In [ ]:
b

array([1, 2, 3, 4])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b = [1., 2.4, 3.5]

In [ ]:
np.array(b, dtype='int64')
# array([1, 2, 3]) 정수로 형변환은 했으나 소수점 이하 버림
# 데이터에 손실 생김

array([1, 2, 3])

In [ ]:
b = [1, 2, 3]
b = np.array(b, dtype='float')

In [ ]:
b

array([1., 2., 3.])

In [ ]:
b.dtype

dtype('float64')

실습 : test2의 strides는 얼마인가요

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

In [ ]:
test2.dtype # 32, 8

dtype('int64')

In [ ]:
test2.strides # (32, 8)

(32, 8)

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

In [ ]:
test3 = test2.T

In [ ]:
test2

array([[15, 20, 25, 30],
       [15, 20, 25, 30]])

In [ ]:
test3.T.strides

(32, 8)

In [ ]:
test4.strides

(8, 32)

# 다차원 배열 기초

## 다차원 배열의 자료형

![alt text](https://lh3.googleusercontent.com/ZhC-hkgaa_zQggBdbQ8J33aW8b6Ubbccwr4dLOiVlXAuJYgBiZzRR0jcrAe9C6h26h_3xfd1UbMt6vwIpLfDffABXNKDkUT6RUZre4-j7DtYt7CFsQ1b4RdNZwfCQoSkr_BWKACQQ42krqB0Jkri4CDHGMhKgALRRiJJaQCsR0frysFtltqxiX0ScqZleBxMkADkJr8FtFKh34ERS4w3lwIqddpWd9ctgu9bJsDA19yNEmLouiwapSV7NwAXgDko3fqxo_W4CY6NU_vXxx8xoyFtaXxdXRCs2yketYJ66IP8Rv_mADUSnXfcCfgHOPlU_PzkT-cLdnfLftHgitAPrDHOqiH7EpLmgg4bO_HWIhpDwfG7iu2upN_rw-sFl64aGj4XhhbPYfmDZpnIEyrvKE4DjycH6rITqxTbhMSWfkeeUBENLusqELkVnPRikaaxYiDVPRuedOp6hNXo7R4A-TghyLn-k61kV3Ruwc14ytOWhZ0BngaDXVo-KF_ZxJUr5GuaFOZbi4UKhXbvnObRZAb0QgKaCdvkYysxU31oryDHpx526hG6SW6b99CxOWbT0lBTy0RoynGz_WVV_ua_umNcmkBNMkt3u04uCUWk8a-BqMG_oVpyqNmqetASSOhCZNbisBzkEgmo4sDbdqsNlFcY3fa-Og8mB1UNmC2uWl5RefSArRAoKn6KxZpcr6qJdl8YWT98ncW6behEO1wLoNsdBg=w526-h413-no)

(source: https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html)

다차원 배열의 원소는 위와 같은 데이터 타입을 가질 수 있습니다.

다차원 배열의 원소는 동일한 데이터 타입을 가져야 합니다.

넘파이가 제공하는 숫자형 자료형은 정수(int), 부호없는 정수(uint), 실수(float), 복소수(complex), 논리(bool)로 총 5가지입니다.

In [ ]:
import numpy as np

In [ ]:
f1 = np.array([1.0, 1., 0.2, .2])

In [ ]:
f1.dtype

dtype('float64')

### number

number 데이터를 입력해서 다차원 배열을 생성해봅시다.

 정수(int), 부호없는 정수(uint), 실수(float), 복소수(complex)가 있습니다.

실습 : 0~9의 정수로 구성된 ndarray 배열 a를 만드세요.

In [ ]:
a = np.arange(10)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a = np.arange(0, 10, .5) # np.arange는 실수로도 규칙을 가진 배열을 만들 수 있습니다

In [ ]:
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

0.0에서 9.0까지 float64 타입의 값이 들어있는 ndarray b를 하나 만들어주세요.

In [ ]:
b = np.arange(0., 10.,)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.array([10.1, 20.1, 30.1], 'int64') # .1 씩 소수점 이하 데이터 손실이 일어납니다

array([10, 20, 30])

In [ ]:
np.array([10, 20, 30], 'float64')

array([10., 20., 30.])

In [ ]:
c # 실수 -> 정수 형변환 : 데이터 손실이 일어나므로 주의하셔야 합니다

array([10, 20, 30])

주의. 정수형에서 실수형으로의 형변환 과정은 데이터 손실이 일어나지 않아 문제될 부분이 없지만 반대의 경우에는 문제가 발생할 수 있습니다.

In [ ]:
a = np.array([10, '20', 30]) # U21

In [ ]:
a + 5

UFuncTypeError: ignored

In [ ]:
a + '가'

UFuncTypeError: ignored

In [ ]:
b = np.array([10, '20', 30], 'int') # int

In [ ]:
b + 5

array([15, 25, 35])

연산을 위한 다차원 배열의 원소는 동일한 데이터 타입을 가져야 합니다.

[10, 20, 30]

#### bool

실습. boolean 데이터를 입력해서 boolArray라는 다차원 배열을 생성해봅시다.

[True, False, True, True, False]

In [ ]:
boolArray = np.array([True, False, True, True, False])
boolArray

array([ True, False,  True,  True, False])

In [ ]:
boolArray.dtype

dtype('bool')

In [ ]:
boolArray + 1 # 플레인 파이썬처럼 numpy의 ndarray도 bool을 숫자로 바꿔서 연산하는구나
# bool도 숫자구나

array([2, 1, 2, 2, 1])

#### (참고) 부호없는 정수형

부호없는 정수형(0을 포함한 양수)의 default data type은 'uint64'입니다.

In [ ]:
uintArray = np.array([[1,2], [3,4]], dtype='uint')
uintArray.dtype

dtype('uint64')

In [ ]:
uintArray = np.array([[-1,-2], [-3,-4]], dtype='uint')
uintArray.dtype

dtype('uint64')

In [ ]:
uintArray

array([[18446744073709551615, 18446744073709551614],
       [18446744073709551613, 18446744073709551612]], dtype=uint64)

#### (참고) 복소수형

복소수형의 default data type은 'complex128'입니다.

In [ ]:
complexArray = np.array([1+1j, 2+2j, 3+3j, 4+4j, 5+5j])

In [ ]:
complexArray

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j, 5.+5.j])

In [ ]:
complexArray.dtype # 양자역학, 반도체, 전기회로

dtype('complex128')

In [ ]:
test[0] = 25

In [ ]:
test

array([25, 20, 25, 30])

## 실습. ndarray 탐색하기

<img src="https://imgconvert.csdnimg.cn/aHR0cHM6Ly93d3cucHl0aG9uaW5mb3JtZXIuY29tL2ltZy9udW1weS8zZC1hcnJheS5wbmc?x-oss-process=image/format,png">

[연결]https://imgconvert.csdnimg.cn/aHR0cHM6Ly93d3cucHl0aG9uaW5mb3JtZXIuY29tL2ltZy9udW1weS8zZC1hcnJheS5wbmc?x-oss-process=image/

실습: 위와 같은 요소로 이루어진 3차원 ndarray를 만들고 a1이라는 이름으로 저장하여 출력하세요.

In [ ]:
a1 = np.array([
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ],
    [
        [20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]
    ],
        [
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]
    ],
])

In [ ]:
type(a1)

numpy.ndarray

실습: a1의 전체 구조를 확인하는 함수, 차원을 확인하는 함수를 통해 구조와 차원을 확인해주세요.

In [ ]:
a1.shape

(3, 3, 3)

In [ ]:
a1.ndim

3

실습. a1에서 원소 14는 어느 위치에 있나요? 인덱싱을 통해 출력해주세요.

In [ ]:
a1[0][1][1]

14

실습. a1에서 원소 24는 어느 위치에 있나요? 인덱싱을 통해 출력해주세요.

In [ ]:
a1[1][1][1]

24

실습. a1에서 아래의 부분만을 찾아 출력하세요.

      [[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]]

In [ ]:
a1[2]

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

실습. a1에서 아래의 부분만을 출력하세요.

      [[[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]],

       [[30, 31, 32],
        [33, 34, 35]]]

In [ ]:
a1[시작점:끝점+1]

In [ ]:
a1[:, :2, :] # 넘파이에서 슬라이싱 i 차원에서 다 쓰겠음, j 차원에서 0, 1, k차원 다쓰겠음

array([[[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]],

       [[30, 31, 32],
        [33, 34, 35]]])

실습. a1에서 아래의 부분만을 출력하세요.

[20, 23]

In [ ]:
a1[1, :2, 0]

array([20, 23])

실습. a1에서 아래의 부분만을 출력하세요.

      [[14, 17],
       [24, 27],
       [34, 37]]

In [ ]:
a2 = a1[:, 1:, 1] # i슬라이싱 j슬라이싱 k인덱싱 # 인덱싱 횟수만큼 차원이 벗겨져서 2차원

In [ ]:
a3 = a1[:, 1:, 1:2]
# i슬라이싱 j슬라이싱 k슬라이싱 - 3차원 모두 활용해서 값 가져옴

In [ ]:
c.ndim, a3.ndim

(2, 3)

In [ ]:
a2.shape

(3, 2)

In [ ]:
a3.shape

(3, 2, 1)

In [ ]:
a3

array([[[14],
        [17]],

       [[24],
        [27]],

       [[34],
        [37]]])

In [ ]:
a4 = a3.reshape(3, 2)

In [ ]:
a3.strides

(72, 24, 8)

In [ ]:
a4.strides

(72, 24)

In [ ]:
a3

array([[[14],
        [17]],

       [[24],
        [27]],

       [[34],
        [37]]])

In [ ]:
a3.shape

(3, 2, 1)

In [ ]:
a4 = a3.reshape(-1, 3) # reshape() 함수를 사용해서 구조를 변경할 때는 말단에 있는 형태는 유지하되 앞부분을 -1로 만들면
# 알아서 말단의 구조를 유지하도록 나머지 차원이 만들어집니다.

In [ ]:
a4

array([[14, 17, 24],
       [27, 34, 37]])

In [ ]:
a4 = a3.reshape(3, 2)

In [ ]:
a4.flatten() # 1차원의 배열로 결과를 만들어준다

array([14, 17, 24, 27, 34, 37])

In [ ]:
a5 = a4.flatten()

In [ ]:
a5

array([14, 17, 24, 27, 34, 37])

In [ ]:
a5.reshape(3,2)

array([[14, 17],
       [24, 27],
       [34, 37]])

In [ ]:
a5.reshape(-1, 2)

array([[14, 17],
       [24, 27],
       [34, 37]])

In [ ]:
a5.reshape(-1, 4) # ValueError: cannot reshape array of size 6 into shape (4)

ValueError: ignored

In [ ]:
a5.shape

(6,)

In [ ]:
a5.reshape(2, -1, 1)

array([[[14],
        [17],
        [24]],

       [[27],
        [34],
        [37]]])

# 자료의 형태
- Scalar: 점, 수 하나. 방향이 없고 양만 있는 것
          파이썬 - 변하지 않는 숫자 (상수) 정도로 이해

- Vector: 선, 한 열이나 행으로 이뤄진 수 조합
          양과 방향성을 가지고 있는 형태
          파이썬 - 행이 n개이고 열이 1인 형태의 배열

- Matrix : 면,
           여러개의 벡터가 모여서 이룬 하나의 행렬을 의미합니다.


In [ ]:
a = 3  # 스칼라

In [ ]:
a = [1, 2, 3, 4, 5] # 행벡터

In [ ]:
b = [
     [1],
     [2],
     [3],
     [4],
     [5],
     ]  # 열벡터

In [ ]:
c = np.array([ [1, 2, 3, 4], [5, 6, 7, 8]])

In [ ]:
c # Matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 특별한 몇가지 벡터 영백터, 일벡터

In [ ]:
np.zeros(4) # 0이 4개 있는 행벡터

array([0., 0., 0., 0.])

In [ ]:
np.zeros((4,1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
np.zeros((4,1)).T

array([[0., 0., 0., 0.]])

In [ ]:
np.zeros((2,3))  # 튜플 형식으로 구조를 지정

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# 0만 4개 들어있는 열벡터를 만들어주세요
np.zeros((4,1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
np.zeros(4, 'int').reshape(-1, 1)

array([[0],
       [0],
       [0],
       [0]])

In [ ]:
np.ones(4, 'int')

array([1, 1, 1, 1])

In [ ]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

# 실습.  c를 3행 2열짜리 행렬로 만들어주세요.

In [ ]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
c.reshape(3, 2)

ValueError: ignored

In [ ]:
c.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
c.reshape(4, -1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# 3행 2열짜리 영벡터를 하나 만들어주세요.

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,2), int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
np.zeros((3,2), bool)

array([[False, False],
       [False, False],
       [False, False]])

## 다차원 배열 만들기

실습. a라는 ndarray를 만들어 아래의 데이터를 넣고 차원과 모양을 확인해보세요.

[10, 20, 30], [40, 50, 60]

In [ ]:
a = np.array([[10, 20, 30], [40, 50, 60]])

In [ ]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a.ndim

2

실습 : [1, 2], [3, 4], [5, 6]의 원소로 구성된 a라는 3차원 행렬을 만들고 출력해보세요.

In [ ]:
a = np.array([
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
])

In [ ]:
a.shape

(1, 3, 2)

In [ ]:
a.ndim

3

In [ ]:
a[0]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a[0][0]

array([1, 2])

In [ ]:
a[0][1]

array([3, 4])

In [ ]:
a[0][2]

array([5, 6])

In [ ]:
a[0][2][0]

5

In [ ]:
a[0, 2, 0]

5

In [ ]:
a[:, 2:, 0]

array([[5]])

In [ ]:
a[:, 2:, 0].reshape(-1)

array([5])

## 넘파이가 제공하는 기본 연산

In [ ]:
np.append(a, 7) # 값을 넣는 메소드

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.insert(a, 2, 20)  # np.insert(배열이름, 값을넣은인덱스번호, 넣을 값)

array([ 1,  2, 20,  3,  4,  5,  6])

In [ ]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
# 4번째 자리에 55라는 값을 넣어주세요
np.insert(a, 3, 55)

array([ 1,  2,  3, 55,  4,  5,  6])

In [ ]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
np.insert(a[0], 1, 55, axis=0)

array([[ 1,  2],
       [55, 55],
       [ 3,  4],
       [ 5,  6]])

In [ ]:
np.insert(a[0], 1, [51, 55], axis=0)

array([[ 1,  2],
       [51, 55],
       [ 3,  4],
       [ 5,  6]])

In [ ]:
np.insert(a[0], 1, [51, 55, 56], axis=0)

ValueError: ignored

In [ ]:
a[0]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.insert(a[0], 1, 55, axis=1)

array([[ 1, 55,  2],
       [ 3, 55,  4],
       [ 5, 55,  6]])

In [ ]:
np.insert(a[0], 1, [55, 54, 53], axis=1)

array([[ 1, 55,  2],
       [ 3, 54,  4],
       [ 5, 53,  6]])

# 무작위 배열을 생성하는 방법

- 교재 224p ~

- 랜덤
    - 파이썬/넘파이의 random은 균등분포를 의미합니다.

In [ ]:
np.random

<module 'numpy.random' from '/usr/local/lib/python3.10/dist-packages/numpy/random/__init__.py'>

In [ ]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponen

In [ ]:
np.random.rand(10) # 0와 1 사이에서 10개 값을 뽑아줌

array([0.15360512, 0.00775279, 0.39178692, 0.33834633, 0.99907837,
       0.53688936, 0.33673072, 0.46745147, 0.08465154, 0.78098866])

In [ ]:
np.random.randint(10) # 0초과 10 미만 어떤 값 1개

9

In [ ]:
np.random.randint(0, 100, 10, dtype=np.uint8) # a, b 사이에서 특정 값 뽑기

array([18, 39, 62, 97, 22, 55, 36, 94, 55, 46], dtype=uint8)

In [ ]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponen

In [ ]:
# 무작위수 n 개 뽑기  - 복원추출 - 중복 o
np.random.choice(5, 3)

array([0, 2, 0])

array([1, 3, 2])

In [ ]:
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0]) # probability
# 0 * p[0] + 1 * p[1] + 2 * p[2] .....

array([2, 2, 3])

In [ ]:
# 랜덤함수들을 실행할 때 최초의 랜덤값(seed)을 똑같이 고정한다면
# seed값은 랜덤함수를 실행하기 전에 먼저 줘야 하고
# 하나의 코드셀 단위로 seed 값이 먹여집니다
np.random.seed(10)
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 0, 3])

In [ ]:
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 2])

### 중복이 아쉽다면

In [ ]:
# 무작위수 n 개 뽑기  - 비복원추출 - 중복 x
np.random.choice(5, 3, replace=False)

## 넘파이가 제공하는 통계연산 메소드

In [ ]:
a = np.array([10, 20, 30, 40]) # 국, 영, 수, 사

In [ ]:
a.mean()

25.0

In [ ]:
np.mean(a)

25.0

In [ ]:
np.average(a, weights=[0.3, 0.3, 0.3, 0.1]) # weights : 가중치

22.000000000000004

In [ ]:
a.mean()

25.0

In [ ]:
np.average(a, weights=[1, 1, 1, 0]) # weights : 가중치

20.0

In [ ]:
a

array([10, 20, 30, 40])

In [ ]:
np.median(a) # 중앙값

25.0

In [ ]:
b = [11, 20, 11, 20, 35]

In [ ]:
np.mean(b)

19.4

In [ ]:
np.median(b)

20.0

In [ ]:
b = [11, 20, 11, 20, 20, 100, 20, 35]
# 우리가 '평균'이라고 말할 때
# 표본집단의 '대표값'을 의미합니다
# 크게 집단의 평균을 의미하는 대표값은 3가지 정도가 있습니다
# : mean(평균), median(중앙값), mode(최빈값 - 넘파이에는 없음)

In [ ]:
np.mode(b) # numpy에는 없음

AttributeError: ignored

In [ ]:
import statistics as st

st.mode(b) # 최빈값을 구할 수 있습니다

20